export const REQUEST = 'POKE_TYPES/REQUEST';
export const SUCCESS = 'POKE_TYPES/SUCCESS';
export const FAILURE = 'POKE_TYPES/FAILURE';
export const SET_SELECTED_TYPE = 'POKE_TYPES/SET_SELECTED_TYPE';
